services:
  - type: static_site
    name: student-plaza-pa-shift-system
    buildCommand: ""
    publishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
